### ISSUE TITLE
Happo not updating GitHub check status on base branch

### ISSUE THREAD

**Issue by matthieu-foucault** [happo/happo.io#166]
Hi, we started using Happo with the Github integration over at https://github.com/bcgov/cas-ciip-portal, using `happo-cypress` to trigger the Happo jobs. We love it so far!

Status checks are correctly reported to PRs, but on our base branch the status check remains "Pending — job started". The Happo job itself is completed (e.g. https://happo.io/a/336/jobs/29680).

The Happo jobs are triggered on CircleCI, and we set `HAPPO_BASE_BRANCH` to be `origin/develop`

**Comment by trotzig** [comment]
Thanks for the report! I’ll look into this after the weekend. Sounds like something isn’t triggered the right way.

Are you using CircleCi, Travis, or a different CI system? This might not matter, I’m just making sure I can debug this in the best possible way.

**Comment by matthieu-foucault** [comment]
Thanks for the quick response!
We use CircleCI. I am wondering if us using a different base branch than the default might have to do with this issue

**Comment by trotzig** [comment]
It shouldn't matter, but I'll make sure to check that.

**Comment by trotzig** [comment]
Sorry for not reporting any results back here. I haven't forgot about it, it's just that other more important things snuck in before I had a chance of addressing this. 🤷 

I hope to look at this during the week though.

**Comment by matthieu-foucault** [comment]
No worries, let me know if I can help debug the issue

**Comment by trotzig** [comment]
Okay, I think I've confirmed this is a race condition. The happo-cypress lib [posts to the create job API endpoint](https://github.com/happo/happo-cypress/blob/1c0d9a2a7fb8143889eb6fb40097c7f0be815755/bin/happo-cypress.js#L117) right after [it has initialized an async-report](https://github.com/happo/happo-cypress/blob/1c0d9a2a7fb8143889eb6fb40097c7f0be815755/bin/happo-cypress.js#L102). In your case, the first call is very fast and posts a "success" status to the commit on GitHub right away. The second call posts a pending "job started" status as well, overriding the initial success status. 

While this could be fixed in the happo-cypress library, I'm going to handle things on the server as well (working on that now). I think other clients might make assumptions about order not being important anyway, so we might as well fix in one place.

**Comment by trotzig** [comment]
I've just deployed a fix for the race-condition to happo.io. I'll close this issue, but feel free to reopen if the issue doesn't go away.

**Comment by matthieu-foucault** [comment]
This is working fine now, thanks!

**Comment by trotzig** [comment]
Excellent, thanks for the report!
